---
  # Make sure to create a file named <service_name>.yml under the tasks directory
  - name: "Include infrastructure custom tasks"
    include: "{{ item }}"
    with_items: "{{ custom_task_files }}"
